spring:
  application:
    name: tech-playground

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    url: ${POSTGRES_DB_HOST}/mydatabase
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
