spring:
  application:
    name: tech-playground
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    url: ${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
